export const SUPPORTED_LANGS = ["en", "fr", "ar", "tr", "zh", "es", "de", "ur", "id", "pt"];

export function normalizeLang(input) {
  const raw = (input || "").toLowerCase();
  if (!raw) return "en";
  const short = raw.split("-")[0];
  return SUPPORTED_LANGS.includes(short) ? short : "en";
}

export const MKT = {
  en: {
    name: "Hifd Quran",
    hero: "Memorize Quran with your own voice",
    desc: "Hifz Quran is a Quran memorization app that uses your own recorded voice to help you memorize through recitation, repetition, and active recall.",
    openApp: "Open App",
    features: "Features",
    about: "About",
    visitMakne: "AI7SKY",
    smartChunking: "Smart Chunking",
    smartChunkingDesc: "Split surahs into practical memorization blocks with overlap for retention.",
    recitationRecording: "Recitation Recording",
    recitationRecordingDesc: "Record every verse and review quality before finalizing your session.",
    progressIntelligence: "Progress Intelligence",
    progressIntelligenceDesc: "Track streaks, completion, and daily consistency for long-term Hifz success.",
    featuresMetaDescription: "Explore Hifd Quran features for Quran memorization, including smart chunking, verse recording, repetition playback, and progress tracking.",
    aboutMetaDescription: "Learn about Hifd Quran, a Quran memorization app designed around voice recording, repetition, and structured Hifz practice.",
    footer: "By the فضل of Allah سبحانه وتعالى · Built by ai7sky.com team · {year}",
    featuresItems: [
      ["Chunk Learning Engine", "Automatic chunk generation with overlap to reinforce memorization continuity."],
      ["Verse-by-Verse Recording", "Record, redo, and save each verse with clear progress steps."],
      ["Adaptive Repetition", "Control verse repetition, chunk repetition, and playback speed."],
      ["Surah Navigation", "Browse surahs, inspect chunk status, and jump directly to practice sessions."],
      ["Progress Insights", "Monitor streaks, completed chunks, and listening totals for accountability."],
      ["Language & Display Controls", "Choose translation language and customize text visibility settings."],
    ],
    aboutParagraphs: [
      "Hifd Quran is designed to support structured Quran memorization using a practical, repeatable, and student-friendly workflow.",
      "The platform combines recitation recording, repetition playback, and progress tracking so learners can build consistency over months and years.",
      "Our vision is to make high-quality Hifz support accessible for students, teachers, and families, while respecting the spiritual nature of Quran learning.",
      "All praise and credit belong first to Allah سبحانه وتعالى, and the project implementation is supported by the ai7sky.com team.",
    ],
  },
  fr: { name: "Hifd Quran", hero: "Mémorisez le Coran intelligemment", desc: "Plateforme de mémorisation du Coran avec répétition, enregistrement et suivi de progression.", openApp: "Ouvrir l'app", features: "Fonctionnalités", about: "À propos", visitMakne: "AI7SKY", smartChunking: "Découpage intelligent", smartChunkingDesc: "Découpez les sourates en blocs pratiques avec chevauchement pour une meilleure rétention.", recitationRecording: "Enregistrement de récitation", recitationRecordingDesc: "Enregistrez chaque verset et vérifiez sa qualité avant de finaliser votre session.", progressIntelligence: "Analyse de progression", progressIntelligenceDesc: "Suivez les séries, l'avancement et la régularité quotidienne pour un Hifz durable.", footer: "Par la grâce d’Allah سبحانه وتعالى · Équipe ai7sky.com · {year}", featuresItems: [["Moteur de découpage", "Génération automatique de blocs avec chevauchement pour renforcer la continuité de mémorisation."],["Enregistrement verset par verset", "Enregistrez, refaites et conservez chaque verset avec des étapes claires."],["Répétition adaptative", "Contrôlez la répétition des versets, des blocs et la vitesse de lecture."],["Navigation des sourates", "Parcourez les sourates, consultez l’état des blocs et accédez directement à la pratique."],["Analyse de progression", "Suivez les séries, les blocs terminés et le temps d’écoute pour rester constant."],["Langue et affichage", "Choisissez la langue de traduction et adaptez l’affichage du texte."]], aboutParagraphs: ["Hifd Quran est conçu pour soutenir une mémorisation structurée du Coran avec un flux pratique et reproductible.", "La plateforme combine enregistrement de récitation, répétition audio et suivi de progression pour renforcer la régularité.", "Notre vision est de rendre un accompagnement Hifz de qualité accessible aux étudiants, enseignants et familles.", "Toute louange et tout mérite reviennent d’abord à Allah سبحانه وتعالى, et la mise en œuvre du projet est soutenue par l’équipe ai7sky.com."] },
  ar: { name: "حفظ القرآن", hero: "احفظ القرآن بتكرار ذكي", desc: "منصة موجهة لحفظ القرآن بالتسجيل والتكرار وتتبع التقدم.", openApp: "فتح التطبيق", features: "المميزات", about: "حول", visitMakne: "AI7SKY", smartChunking: "التقسيم الذكي", smartChunkingDesc: "قسّم السور إلى مقاطع عملية مع تداخل يساعد على ترسيخ الحفظ.", recitationRecording: "تسجيل التلاوة", recitationRecordingDesc: "سجّل كل آية وراجع الجودة قبل اعتماد الجلسة.", progressIntelligence: "ذكاء التقدم", progressIntelligenceDesc: "تابع الاستمرارية والإنجاز والمواظبة اليومية لحفظ طويل المدى.", footer: "بفضل الله سبحانه وتعالى · فريق ai7sky.com · {year}", featuresItems: [["محرك تقسيم المقاطع", "إنشاء تلقائي للمقاطع مع تداخل يساعد على تثبيت الحفظ."],["تسجيل آية بآية", "سجّل كل آية وأعدها واحفظها بخطوات واضحة."],["تكرار مرن", "تحكّم في تكرار الآيات والمقاطع وسرعة التشغيل."],["التنقل بين السور", "تصفح السور وراجع حالة المقاطع وانتقل مباشرة إلى جلسات التدريب."],["رؤى التقدم", "تابع الاستمرارية والمقاطع المكتملة وإجمالي الاستماع للمحاسبة."],["اللغة وإعدادات العرض", "اختر لغة الترجمة واضبط طريقة عرض النص."]], aboutParagraphs: ["تم تصميم حفظ القرآن لدعم حفظ القرآن بطريقة عملية ومنظمة وقابلة للتكرار.", "تجمع المنصة بين تسجيل التلاوة والتكرار وتتبع التقدم لمساعدة المتعلم على الاستمرار لمدد طويلة.", "رؤيتنا هي توفير دعم عالي الجودة للحفظ للطلاب والمعلمين والأسر مع احترام طبيعة تعلم القرآن الروحية.", "الحمد والفضل أولًا لله سبحانه وتعالى، وتنفيذ المشروع بدعم من فريق ai7sky.com."] },
  tr: { name: "Hifd Quran", hero: "Akıllı tekrar ile Kur'an ezberi", desc: "Kayıt, tekrar ve ilerleme takibi ile yapılandırılmış ezber platformu.", openApp: "Uygulamayı Aç", features: "Özellikler", about: "Hakkında", visitMakne: "Makne.app'i ziyaret et", smartChunking: "Akıllı Parçalama", smartChunkingDesc: "Sureleri, kalıcılığı artıran örtüşmeli pratik ezber bloklarına ayırın.", recitationRecording: "Tilavet Kaydı", recitationRecordingDesc: "Her ayeti kaydedin ve oturumu tamamlamadan önce kaliteyi gözden geçirin.", progressIntelligence: "İlerleme Zekâsı", progressIntelligenceDesc: "Uzun vadeli Hıfz başarısı için serileri, tamamlanmayı ve günlük istikrarı takip edin.", footer: "© {year} Hifd Quran · hifdquran.los.ma", featuresItems: [["Parça Öğrenme Motoru", "Ezber sürekliliğini güçlendirmek için örtüşmeli otomatik parça üretimi."],["Ayet Bazlı Kayıt", "Her ayeti kaydedin, yeniden okuyun ve net adımlarla saklayın."],["Uyarlanabilir Tekrar", "Ayet tekrarı, parça tekrarı ve oynatma hızını kontrol edin."],["Sure Gezinme", "Surelere göz atın, parça durumlarını inceleyin ve doğrudan çalışmaya geçin."],["İlerleme İçgörüleri", "Serileri, tamamlanan parçaları ve dinleme toplamlarını izleyin."],["Dil ve Görünüm Kontrolleri", "Çeviri dilini seçin ve metin görünümünü özelleştirin."]], aboutParagraphs: ["Hifd Quran, yapılandırılmış Kur'an ezberini pratik ve tekrar edilebilir bir akışla desteklemek için tasarlanmıştır.", "Platform; tilavet kaydı, tekrar oynatma ve ilerleme takibini birleştirerek düzenli çalışmayı destekler.", "Vizyonumuz, kaliteli Hıfz desteğini öğrenciler, öğretmenler ve aileler için erişilebilir kılmaktır."] },
  zh: { name: "Hifd Quran", hero: "智能重复辅助古兰经记忆", desc: "通过录音、重复和进度追踪进行系统化背诵。", openApp: "打开应用", features: "功能", about: "关于", visitMakne: "访问 Makne.app", smartChunking: "智能分段", smartChunkingDesc: "将章节拆分为带有重叠复习的实用记忆块，以增强记忆。", recitationRecording: "诵读录音", recitationRecordingDesc: "录下每节经文，并在完成学习前检查质量。", progressIntelligence: "进度洞察", progressIntelligenceDesc: "跟踪连续性、完成度和每日坚持，支持长期背诵。", footer: "© {year} Hifd Quran · hifdquran.los.ma", featuresItems: [["分段学习引擎", "自动生成带重叠复习的记忆分段，增强持续记忆。"],["逐节录音", "录下、重录并保存每一节，步骤清晰。"],["自适应重复", "控制经文重复、分段重复和播放速度。"],["章节导航", "浏览章节、查看分段状态，并直接进入练习。"],["进度洞察", "跟踪连续性、已完成分段和收听总量。"],["语言与显示控制", "选择翻译语言并自定义文本显示。"]], aboutParagraphs: ["Hifd Quran 旨在通过实用、可重复的流程支持结构化古兰经记忆。", "平台结合诵读录音、重复播放和进度追踪，帮助学习者长期保持稳定。", "我们的愿景是为学生、教师和家庭提供高质量、易获得的 Hifz 支持。"] },
  es: { name: "Hifd Quran", hero: "Memoriza el Corán con repetición inteligente", desc: "Plataforma para Hifz con grabación, repetición y seguimiento de progreso.", openApp: "Abrir App", features: "Funciones", about: "Acerca de", visitMakne: "Visitar Makne.app", smartChunking: "Fragmentación inteligente", smartChunkingDesc: "Divide las suras en bloques prácticos con solapamiento para reforzar la retención.", recitationRecording: "Grabación de recitación", recitationRecordingDesc: "Graba cada aleya y revisa la calidad antes de finalizar tu sesión.", progressIntelligence: "Inteligencia de progreso", progressIntelligenceDesc: "Sigue rachas, progreso y constancia diaria para un Hifz duradero.", footer: "© {year} Hifd Quran · hifdquran.los.ma", featuresItems: [["Motor de bloques", "Generación automática de bloques con solapamiento para reforzar la memorización."],["Grabación verso por verso", "Graba, repite y guarda cada aleya con pasos claros."],["Repetición adaptativa", "Controla la repetición de versos, bloques y la velocidad de reproducción."],["Navegación por suras", "Explora suras, revisa el estado de los bloques y entra directamente en la práctica."],["Perspectivas de progreso", "Sigue rachas, bloques completados y tiempo de escucha."],["Idioma y visualización", "Elige el idioma de traducción y personaliza la visualización del texto."]], aboutParagraphs: ["Hifd Quran está diseñado para apoyar una memorización estructurada del Corán con un flujo práctico y repetible.", "La plataforma combina grabación de recitación, reproducción repetida y seguimiento del progreso para construir constancia.", "Nuestra visión es hacer accesible un apoyo de Hifz de alta calidad para estudiantes, docentes y familias."] },
  de: { name: "Hifd Quran", hero: "Koran auswendig lernen mit smarter Wiederholung", desc: "Strukturierte Hifz-Plattform mit Aufnahme, Wiederholung und Fortschrittstracking.", openApp: "App öffnen", features: "Funktionen", about: "Über", visitMakne: "Makne.app besuchen", smartChunking: "Intelligente Aufteilung", smartChunkingDesc: "Teile Suren in praktische Lernabschnitte mit Überlappung zur besseren Behaltensleistung.", recitationRecording: "Rezitationsaufnahme", recitationRecordingDesc: "Nimm jeden Vers auf und überprüfe die Qualität, bevor du deine Sitzung abschließt.", progressIntelligence: "Fortschrittsanalyse", progressIntelligenceDesc: "Verfolge Serien, Abschlüsse und tägliche Beständigkeit für langfristigen Hifz-Erfolg.", footer: "© {year} Hifd Quran · hifdquran.los.ma", featuresItems: [["Lernblöcke-Engine", "Automatische Blockerstellung mit Überlappung zur Verstärkung der Memorierungskontinuität."],["Vers-für-Vers-Aufnahme", "Nimm jeden Vers auf, wiederhole ihn und speichere ihn mit klaren Schritten."],["Adaptive Wiederholung", "Steuere Verswiederholung, Blockwiederholung und Wiedergabegeschwindigkeit."],["Suren-Navigation", "Durchsuche Suren, prüfe Blockstatus und springe direkt in die Übung."],["Fortschritts-Einblicke", "Verfolge Serien, abgeschlossene Blöcke und Hörzeiten zur Selbstkontrolle."],["Sprach- und Anzeigeoptionen", "Wähle die Übersetzungssprache und passe die Textanzeige an."]], aboutParagraphs: ["Hifd Quran wurde entwickelt, um strukturiertes Koranauswendiglernen mit einem praktischen und wiederholbaren Ablauf zu unterstützen.", "Die Plattform verbindet Rezitationsaufnahme, Wiederholungswiedergabe und Fortschrittsverfolgung für langfristige Beständigkeit.", "Unsere Vision ist es, hochwertigen Hifz-Support für Schüler, Lehrkräfte und Familien zugänglich zu machen."] },
  ur: { name: "حفظ قرآن", hero: "سمارٹ ریپیٹیشن کے ساتھ قرآن حفظ کریں", desc: "ریکارڈنگ، تکرار اور پروگریس ٹریکنگ کے ساتھ حفظ کا منظم نظام۔", openApp: "ایپ کھولیں", features: "خصوصیات", about: "تعارف", visitMakne: "Makne.app دیکھیں", smartChunking: "سمارٹ چنکنگ", smartChunkingDesc: "سوروں کو حفظ کے لیے عملی حصوں میں تقسیم کریں تاکہ یادداشت مضبوط ہو۔", recitationRecording: "تلاوت ریکارڈنگ", recitationRecordingDesc: "ہر آیت ریکارڈ کریں اور سیشن مکمل کرنے سے پہلے معیار دیکھیں۔", progressIntelligence: "پیش رفت کی بصیرت", progressIntelligenceDesc: "طویل مدتی حفظ کے لیے تسلسل، تکمیل اور روزانہ پابندی کو ٹریک کریں۔", footer: "© {year} حفظ قرآن · hifdquran.los.ma", featuresItems: [["چنک لرننگ انجن", "حفظ کی روانی کے لیے خودکار چنکنگ اور اوورلیپ۔"],["آیت بہ آیت ریکارڈنگ", "ہر آیت ریکارڈ کریں، دوبارہ کریں اور واضح مراحل کے ساتھ محفوظ کریں۔"],["مطابق تکرار", "آیت، چنک اور رفتار کی تکرار کو قابو میں رکھیں۔"],["سورہ نیویگیشن", "سورتیں براؤز کریں، چنک کی حالت دیکھیں اور سیدھا مشق پر جائیں۔"],["پیش رفت کی بصیرت", "استقامت، مکمل شدہ حصے اور سننے کے وقت کو ٹریک کریں۔"],["زبان اور ڈسپلے کنٹرولز", "ترجمے کی زبان منتخب کریں اور متن کی نمائش کو حسبِ ضرورت بنائیں۔"]], aboutParagraphs: ["حفظ قرآن کو اس طرح ڈیزائن کیا گیا ہے کہ یہ قرآن کے منظم حفظ کو عملی اور دہرائے جانے والے انداز میں سہارا دے۔", "یہ پلیٹ فارم تلاوت کی ریکارڈنگ، تکراری پلے بیک اور پیش رفت کی نگرانی کو یکجا کرتا ہے۔", "ہماری نظر یہ ہے کہ معیاری حفظ سپورٹ طلبہ، اساتذہ اور خاندانوں کے لیے قابلِ رسائی ہو۔"] },
  id: { name: "Hifd Quran", hero: "Hafal Quran dengan pengulangan cerdas", desc: "Platform Hifz terstruktur dengan rekaman, pengulangan, dan pelacakan progres.", openApp: "Buka Aplikasi", features: "Fitur", about: "Tentang", visitMakne: "Kunjungi Makne.app", smartChunking: "Pembagian Cerdas", smartChunkingDesc: "Bagi surah menjadi blok hafalan praktis dengan tumpang tindih untuk retensi lebih baik.", recitationRecording: "Rekaman Tilawah", recitationRecordingDesc: "Rekam setiap ayat dan tinjau kualitasnya sebelum menyelesaikan sesi.", progressIntelligence: "Kecerdasan Progres", progressIntelligenceDesc: "Pantau konsistensi, penyelesaian, dan kebiasaan harian untuk Hifz jangka panjang.", footer: "© {year} Hifd Quran · hifdquran.los.ma", featuresItems: [["Mesin Pembelajaran Blok", "Pembuatan blok otomatis dengan tumpang tindih untuk memperkuat kesinambungan hafalan."],["Rekaman Ayat per Ayat", "Rekam, ulangi, dan simpan setiap ayat dengan langkah yang jelas."],["Pengulangan Adaptif", "Atur pengulangan ayat, blok, dan kecepatan pemutaran."],["Navigasi Surah", "Jelajahi surah, lihat status blok, dan langsung masuk ke sesi latihan."],["Wawasan Progres", "Pantau streak, blok selesai, dan total durasi mendengar."],["Kontrol Bahasa & Tampilan", "Pilih bahasa terjemahan dan sesuaikan tampilan teks."]], aboutParagraphs: ["Hifd Quran dirancang untuk mendukung hafalan Quran terstruktur dengan alur yang praktis dan dapat diulang.", "Platform ini menggabungkan rekaman tilawah, pemutaran berulang, dan pelacakan progres agar konsistensi terjaga.", "Visi kami adalah menghadirkan dukungan Hifz berkualitas tinggi bagi pelajar, guru, dan keluarga."] },
  pt: { name: "Hifd Quran", hero: "Memorize o Alcorão com repetição inteligente", desc: "Plataforma de Hifz com gravação, repetição e acompanhamento de progresso.", openApp: "Abrir App", features: "Recursos", about: "Sobre", visitMakne: "Visitar Makne.app", smartChunking: "Divisão Inteligente", smartChunkingDesc: "Divida as suratas em blocos práticos com sobreposição para reforçar a retenção.", recitationRecording: "Gravação da Recitação", recitationRecordingDesc: "Grave cada versículo e revise a qualidade antes de finalizar sua sessão.", progressIntelligence: "Inteligência de Progresso", progressIntelligenceDesc: "Acompanhe sequências, conclusão e consistência diária para um Hifz duradouro.", footer: "© {year} Hifd Quran · hifdquran.los.ma", featuresItems: [["Motor de Blocos", "Geração automática de blocos com sobreposição para reforçar a continuidade da memorização."],["Gravação Verso por Verso", "Grave, refaça e salve cada versículo com passos claros."],["Repetição Adaptativa", "Controle a repetição de versos, blocos e a velocidade de reprodução."],["Navegação por Suratas", "Navegue pelas suratas, veja o estado dos blocos e vá direto para a prática."],["Visão de Progresso", "Acompanhe sequências, blocos concluídos e total de escuta."],["Idioma e Exibição", "Escolha o idioma da tradução e personalize a exibição do texto."]], aboutParagraphs: ["Hifd Quran foi criado para apoiar a memorização estruturada do Alcorão com um fluxo prático e repetível.", "A plataforma combina gravação da recitação, repetição de áudio e acompanhamento do progresso para fortalecer a consistência.", "Nossa visão é tornar um suporte de Hifz de alta qualidade acessível a estudantes, professores e famílias."] },
};
